//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: acx
// Function header: acxFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createacxFunctionMap();

extern "C"  {


	XSCCall      acxfunc;
	XSCCall      vacxfunc;
	XSCCall      acxion;
}


#endif
