//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: acx
// Function body: acxFunctionMap.cxx

#include    "acxFunctionMap.h"

#include    <XSModelFunction.h>

void 
createacxFunctionMap()
{


	XSFunctionMap["acx"]      = new XSCall<XSCCall>(acxfunc);
	XSFunctionMap["vacx"]     = new XSCall<XSCCall>(vacxfunc);
	XSFunctionMap["acxion"]   = new XSCall<XSCCall>(acxion);

}
